--Fallo de inserción en las filas  1  mediante  1000 
--ORA-00001: restricción única (ISIS2304B161820.CATEGORIA_PK) violada
--Fila 1
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (1.0,'Electronics');
--Fila 2
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (2.0,'Shoes');
--Fila 3
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (3.0,'Computers');
--Fila 4
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (4.0,'Movies');
--Fila 5
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (5.0,'Electronics');
--Fila 6
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (6.0,'Books');
--Fila 7
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (7.0,'Garden');
--Fila 8
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (8.0,'Toys');
--Fila 9
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (9.0,'Industrial');
--Fila 10
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (10.0,'Jewelery');
--Fila 11
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (11.0,'Beauty');
--Fila 12
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (12.0,'Movies');
--Fila 13
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (13.0,'Clothing');
--Fila 14
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (14.0,'Outdoors');
--Fila 15
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (15.0,'Garden');
--Fila 16
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (16.0,'Games');
--Fila 17
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (17.0,'Sports');
--Fila 18
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (18.0,'Books');
--Fila 19
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (19.0,'Books');
--Fila 20
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (20.0,'Books');
--Fila 21
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (21.0,'Garden');
--Fila 22
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (22.0,'Baby');
--Fila 23
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (23.0,'Music');
--Fila 24
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (24.0,'Grocery');
--Fila 25
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (25.0,'Grocery');
--Fila 26
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (26.0,'Outdoors');
--Fila 27
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (27.0,'Baby');
--Fila 28
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (28.0,'Music');
--Fila 29
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (29.0,'Computers');
--Fila 30
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (30.0,'Books');
--Fila 31
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (31.0,'Sports');
--Fila 32
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (32.0,'Tools');
--Fila 33
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (33.0,'Toys');
--Fila 34
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (34.0,'Baby');
--Fila 35
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (35.0,'Clothing');
--Fila 36
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (36.0,'Automotive');
--Fila 37
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (37.0,'Health');
--Fila 38
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (38.0,'Computers');
--Fila 39
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (39.0,'Automotive');
--Fila 40
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (40.0,'Health');
--Fila 41
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (41.0,'Music');
--Fila 42
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (42.0,'Shoes');
--Fila 43
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (43.0,'Music');
--Fila 44
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (44.0,'Computers');
--Fila 45
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (45.0,'Outdoors');
--Fila 46
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (46.0,'Kids');
--Fila 47
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (47.0,'Computers');
--Fila 48
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (48.0,'Computers');
--Fila 49
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (49.0,'Industrial');
--Fila 50
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (50.0,'Grocery');
--Fila 51
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (51.0,'Music');
--Fila 52
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (52.0,'Shoes');
--Fila 53
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (53.0,'Electronics');
--Fila 54
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (54.0,'Health');
--Fila 55
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (55.0,'Clothing');
--Fila 56
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (56.0,'Computers');
--Fila 57
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (57.0,'Grocery');
--Fila 58
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (58.0,'Toys');
--Fila 59
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (59.0,'Toys');
--Fila 60
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (60.0,'Outdoors');
--Fila 61
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (61.0,'Garden');
--Fila 62
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (62.0,'Industrial');
--Fila 63
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (63.0,'Industrial');
--Fila 64
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (64.0,'Garden');
--Fila 65
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (65.0,'Health');
--Fila 66
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (66.0,'Tools');
--Fila 67
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (67.0,'Sports');
--Fila 68
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (68.0,'Kids');
--Fila 69
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (69.0,'Sports');
--Fila 70
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (70.0,'Kids');
--Fila 71
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (71.0,'Books');
--Fila 72
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (72.0,'Movies');
--Fila 73
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (73.0,'Grocery');
--Fila 74
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (74.0,'Tools');
--Fila 75
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (75.0,'Clothing');
--Fila 76
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (76.0,'Electronics');
--Fila 77
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (77.0,'Outdoors');
--Fila 78
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (78.0,'Sports');
--Fila 79
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (79.0,'Grocery');
--Fila 80
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (80.0,'Toys');
--Fila 81
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (81.0,'Outdoors');
--Fila 82
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (82.0,'Kids');
--Fila 83
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (83.0,'Beauty');
--Fila 84
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (84.0,'Outdoors');
--Fila 85
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (85.0,'Games');
--Fila 86
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (86.0,'Automotive');
--Fila 87
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (87.0,'Beauty');
--Fila 88
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (88.0,'Toys');
--Fila 89
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (89.0,'Toys');
--Fila 90
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (90.0,'Shoes');
--Fila 91
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (91.0,'Electronics');
--Fila 92
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (92.0,'Beauty');
--Fila 93
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (93.0,'Baby');
--Fila 94
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (94.0,'Jewelery');
--Fila 95
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (95.0,'Jewelery');
--Fila 96
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (96.0,'Grocery');
--Fila 97
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (97.0,'Games');
--Fila 98
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (98.0,'Clothing');
--Fila 99
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (99.0,'Computers');
--Fila 100
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (100.0,'Home');
--Fila 101
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (101.0,'Beauty');
--Fila 102
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (102.0,'Industrial');
--Fila 103
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (103.0,'Electronics');
--Fila 104
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (104.0,'Outdoors');
--Fila 105
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (105.0,'Shoes');
--Fila 106
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (106.0,'Industrial');
--Fila 107
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (107.0,'Jewelery');
--Fila 108
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (108.0,'Grocery');
--Fila 109
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (109.0,'Health');
--Fila 110
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (110.0,'Industrial');
--Fila 111
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (111.0,'Shoes');
--Fila 112
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (112.0,'Industrial');
--Fila 113
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (113.0,'Toys');
--Fila 114
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (114.0,'Garden');
--Fila 115
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (115.0,'Grocery');
--Fila 116
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (116.0,'Shoes');
--Fila 117
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (117.0,'Shoes');
--Fila 118
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (118.0,'Garden');
--Fila 119
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (119.0,'Electronics');
--Fila 120
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (120.0,'Books');
--Fila 121
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (121.0,'Toys');
--Fila 122
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (122.0,'Music');
--Fila 123
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (123.0,'Computers');
--Fila 124
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (124.0,'Games');
--Fila 125
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (125.0,'Kids');
--Fila 126
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (126.0,'Baby');
--Fila 127
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (127.0,'Clothing');
--Fila 128
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (128.0,'Sports');
--Fila 129
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (129.0,'Tools');
--Fila 130
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (130.0,'Clothing');
--Fila 131
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (131.0,'Games');
--Fila 132
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (132.0,'Industrial');
--Fila 133
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (133.0,'Baby');
--Fila 134
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (134.0,'Games');
--Fila 135
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (135.0,'Automotive');
--Fila 136
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (136.0,'Games');
--Fila 137
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (137.0,'Movies');
--Fila 138
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (138.0,'Electronics');
--Fila 139
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (139.0,'Industrial');
--Fila 140
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (140.0,'Grocery');
--Fila 141
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (141.0,'Clothing');
--Fila 142
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (142.0,'Automotive');
--Fila 143
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (143.0,'Tools');
--Fila 144
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (144.0,'Shoes');
--Fila 145
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (145.0,'Music');
--Fila 146
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (146.0,'Garden');
--Fila 147
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (147.0,'Health');
--Fila 148
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (148.0,'Industrial');
--Fila 149
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (149.0,'Shoes');
--Fila 150
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (150.0,'Grocery');
--Fila 151
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (151.0,'Kids');
--Fila 152
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (152.0,'Beauty');
--Fila 153
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (153.0,'Shoes');
--Fila 154
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (154.0,'Kids');
--Fila 155
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (155.0,'Computers');
--Fila 156
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (156.0,'Movies');
--Fila 157
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (157.0,'Toys');
--Fila 158
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (158.0,'Jewelery');
--Fila 159
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (159.0,'Automotive');
--Fila 160
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (160.0,'Shoes');
--Fila 161
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (161.0,'Movies');
--Fila 162
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (162.0,'Movies');
--Fila 163
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (163.0,'Tools');
--Fila 164
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (164.0,'Music');
--Fila 165
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (165.0,'Baby');
--Fila 166
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (166.0,'Health');
--Fila 167
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (167.0,'Books');
--Fila 168
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (168.0,'Shoes');
--Fila 169
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (169.0,'Outdoors');
--Fila 170
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (170.0,'Games');
--Fila 171
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (171.0,'Toys');
--Fila 172
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (172.0,'Music');
--Fila 173
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (173.0,'Sports');
--Fila 174
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (174.0,'Home');
--Fila 175
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (175.0,'Outdoors');
--Fila 176
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (176.0,'Beauty');
--Fila 177
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (177.0,'Baby');
--Fila 178
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (178.0,'Games');
--Fila 179
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (179.0,'Outdoors');
--Fila 180
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (180.0,'Sports');
--Fila 181
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (181.0,'Shoes');
--Fila 182
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (182.0,'Kids');
--Fila 183
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (183.0,'Music');
--Fila 184
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (184.0,'Industrial');
--Fila 185
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (185.0,'Toys');
--Fila 186
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (186.0,'Baby');
--Fila 187
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (187.0,'Electronics');
--Fila 188
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (188.0,'Outdoors');
--Fila 189
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (189.0,'Jewelery');
--Fila 190
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (190.0,'Games');
--Fila 191
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (191.0,'Beauty');
--Fila 192
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (192.0,'Shoes');
--Fila 193
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (193.0,'Home');
--Fila 194
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (194.0,'Kids');
--Fila 195
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (195.0,'Garden');
--Fila 196
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (196.0,'Clothing');
--Fila 197
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (197.0,'Games');
--Fila 198
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (198.0,'Games');
--Fila 199
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (199.0,'Kids');
--Fila 200
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (200.0,'Outdoors');
--Fila 201
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (201.0,'Home');
--Fila 202
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (202.0,'Kids');
--Fila 203
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (203.0,'Jewelery');
--Fila 204
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (204.0,'Health');
--Fila 205
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (205.0,'Grocery');
--Fila 206
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (206.0,'Books');
--Fila 207
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (207.0,'Jewelery');
--Fila 208
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (208.0,'Games');
--Fila 209
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (209.0,'Toys');
--Fila 210
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (210.0,'Kids');
--Fila 211
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (211.0,'Automotive');
--Fila 212
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (212.0,'Industrial');
--Fila 213
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (213.0,'Grocery');
--Fila 214
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (214.0,'Baby');
--Fila 215
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (215.0,'Garden');
--Fila 216
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (216.0,'Movies');
--Fila 217
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (217.0,'Kids');
--Fila 218
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (218.0,'Shoes');
--Fila 219
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (219.0,'Books');
--Fila 220
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (220.0,'Shoes');
--Fila 221
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (221.0,'Automotive');
--Fila 222
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (222.0,'Outdoors');
--Fila 223
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (223.0,'Shoes');
--Fila 224
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (224.0,'Automotive');
--Fila 225
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (225.0,'Computers');
--Fila 226
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (226.0,'Music');
--Fila 227
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (227.0,'Electronics');
--Fila 228
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (228.0,'Computers');
--Fila 229
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (229.0,'Automotive');
--Fila 230
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (230.0,'Shoes');
--Fila 231
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (231.0,'Baby');
--Fila 232
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (232.0,'Beauty');
--Fila 233
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (233.0,'Automotive');
--Fila 234
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (234.0,'Shoes');
--Fila 235
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (235.0,'Kids');
--Fila 236
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (236.0,'Grocery');
--Fila 237
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (237.0,'Baby');
--Fila 238
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (238.0,'Electronics');
--Fila 239
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (239.0,'Movies');
--Fila 240
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (240.0,'Books');
--Fila 241
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (241.0,'Garden');
--Fila 242
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (242.0,'Tools');
--Fila 243
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (243.0,'Tools');
--Fila 244
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (244.0,'Computers');
--Fila 245
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (245.0,'Sports');
--Fila 246
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (246.0,'Automotive');
--Fila 247
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (247.0,'Outdoors');
--Fila 248
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (248.0,'Automotive');
--Fila 249
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (249.0,'Outdoors');
--Fila 250
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (250.0,'Beauty');
--Fila 251
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (251.0,'Garden');
--Fila 252
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (252.0,'Automotive');
--Fila 253
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (253.0,'Tools');
--Fila 254
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (254.0,'Computers');
--Fila 255
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (255.0,'Music');
--Fila 256
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (256.0,'Home');
--Fila 257
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (257.0,'Baby');
--Fila 258
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (258.0,'Kids');
--Fila 259
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (259.0,'Home');
--Fila 260
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (260.0,'Automotive');
--Fila 261
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (261.0,'Toys');
--Fila 262
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (262.0,'Industrial');
--Fila 263
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (263.0,'Grocery');
--Fila 264
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (264.0,'Garden');
--Fila 265
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (265.0,'Toys');
--Fila 266
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (266.0,'Outdoors');
--Fila 267
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (267.0,'Electronics');
--Fila 268
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (268.0,'Garden');
--Fila 269
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (269.0,'Movies');
--Fila 270
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (270.0,'Toys');
--Fila 271
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (271.0,'Jewelery');
--Fila 272
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (272.0,'Tools');
--Fila 273
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (273.0,'Clothing');
--Fila 274
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (274.0,'Games');
--Fila 275
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (275.0,'Health');
--Fila 276
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (276.0,'Books');
--Fila 277
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (277.0,'Games');
--Fila 278
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (278.0,'Clothing');
--Fila 279
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (279.0,'Computers');
--Fila 280
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (280.0,'Health');
--Fila 281
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (281.0,'Outdoors');
--Fila 282
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (282.0,'Industrial');
--Fila 283
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (283.0,'Computers');
--Fila 284
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (284.0,'Tools');
--Fila 285
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (285.0,'Movies');
--Fila 286
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (286.0,'Games');
--Fila 287
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (287.0,'Books');
--Fila 288
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (288.0,'Movies');
--Fila 289
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (289.0,'Grocery');
--Fila 290
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (290.0,'Garden');
--Fila 291
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (291.0,'Home');
--Fila 292
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (292.0,'Toys');
--Fila 293
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (293.0,'Tools');
--Fila 294
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (294.0,'Sports');
--Fila 295
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (295.0,'Automotive');
--Fila 296
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (296.0,'Clothing');
--Fila 297
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (297.0,'Garden');
--Fila 298
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (298.0,'Games');
--Fila 299
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (299.0,'Movies');
--Fila 300
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (300.0,'Toys');
--Fila 301
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (301.0,'Music');
--Fila 302
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (302.0,'Baby');
--Fila 303
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (303.0,'Toys');
--Fila 304
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (304.0,'Automotive');
--Fila 305
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (305.0,'Tools');
--Fila 306
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (306.0,'Clothing');
--Fila 307
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (307.0,'Jewelery');
--Fila 308
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (308.0,'Baby');
--Fila 309
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (309.0,'Baby');
--Fila 310
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (310.0,'Baby');
--Fila 311
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (311.0,'Movies');
--Fila 312
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (312.0,'Kids');
--Fila 313
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (313.0,'Tools');
--Fila 314
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (314.0,'Games');
--Fila 315
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (315.0,'Kids');
--Fila 316
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (316.0,'Automotive');
--Fila 317
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (317.0,'Outdoors');
--Fila 318
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (318.0,'Automotive');
--Fila 319
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (319.0,'Shoes');
--Fila 320
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (320.0,'Baby');
--Fila 321
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (321.0,'Music');
--Fila 322
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (322.0,'Health');
--Fila 323
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (323.0,'Books');
--Fila 324
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (324.0,'Toys');
--Fila 325
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (325.0,'Clothing');
--Fila 326
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (326.0,'Industrial');
--Fila 327
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (327.0,'Health');
--Fila 328
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (328.0,'Jewelery');
--Fila 329
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (329.0,'Computers');
--Fila 330
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (330.0,'Movies');
--Fila 331
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (331.0,'Kids');
--Fila 332
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (332.0,'Health');
--Fila 333
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (333.0,'Automotive');
--Fila 334
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (334.0,'Music');
--Fila 335
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (335.0,'Books');
--Fila 336
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (336.0,'Computers');
--Fila 337
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (337.0,'Electronics');
--Fila 338
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (338.0,'Garden');
--Fila 339
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (339.0,'Industrial');
--Fila 340
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (340.0,'Games');
--Fila 341
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (341.0,'Music');
--Fila 342
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (342.0,'Clothing');
--Fila 343
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (343.0,'Music');
--Fila 344
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (344.0,'Tools');
--Fila 345
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (345.0,'Shoes');
--Fila 346
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (346.0,'Outdoors');
--Fila 347
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (347.0,'Health');
--Fila 348
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (348.0,'Jewelery');
--Fila 349
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (349.0,'Baby');
--Fila 350
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (350.0,'Toys');
--Fila 351
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (351.0,'Industrial');
--Fila 352
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (352.0,'Toys');
--Fila 353
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (353.0,'Grocery');
--Fila 354
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (354.0,'Clothing');
--Fila 355
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (355.0,'Health');
--Fila 356
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (356.0,'Kids');
--Fila 357
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (357.0,'Home');
--Fila 358
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (358.0,'Shoes');
--Fila 359
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (359.0,'Jewelery');
--Fila 360
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (360.0,'Automotive');
--Fila 361
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (361.0,'Kids');
--Fila 362
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (362.0,'Tools');
--Fila 363
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (363.0,'Computers');
--Fila 364
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (364.0,'Electronics');
--Fila 365
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (365.0,'Computers');
--Fila 366
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (366.0,'Electronics');
--Fila 367
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (367.0,'Grocery');
--Fila 368
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (368.0,'Kids');
--Fila 369
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (369.0,'Toys');
--Fila 370
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (370.0,'Movies');
--Fila 371
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (371.0,'Beauty');
--Fila 372
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (372.0,'Jewelery');
--Fila 373
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (373.0,'Sports');
--Fila 374
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (374.0,'Industrial');
--Fila 375
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (375.0,'Beauty');
--Fila 376
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (376.0,'Electronics');
--Fila 377
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (377.0,'Kids');
--Fila 378
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (378.0,'Home');
--Fila 379
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (379.0,'Garden');
--Fila 380
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (380.0,'Industrial');
--Fila 381
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (381.0,'Movies');
--Fila 382
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (382.0,'Movies');
--Fila 383
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (383.0,'Shoes');
--Fila 384
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (384.0,'Games');
--Fila 385
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (385.0,'Books');
--Fila 386
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (386.0,'Health');
--Fila 387
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (387.0,'Books');
--Fila 388
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (388.0,'Sports');
--Fila 389
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (389.0,'Sports');
--Fila 390
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (390.0,'Movies');
--Fila 391
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (391.0,'Outdoors');
--Fila 392
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (392.0,'Grocery');
--Fila 393
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (393.0,'Tools');
--Fila 394
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (394.0,'Music');
--Fila 395
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (395.0,'Books');
--Fila 396
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (396.0,'Garden');
--Fila 397
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (397.0,'Jewelery');
--Fila 398
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (398.0,'Music');
--Fila 399
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (399.0,'Movies');
--Fila 400
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (400.0,'Automotive');
--Fila 401
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (401.0,'Home');
--Fila 402
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (402.0,'Health');
--Fila 403
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (403.0,'Tools');
--Fila 404
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (404.0,'Games');
--Fila 405
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (405.0,'Automotive');
--Fila 406
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (406.0,'Baby');
--Fila 407
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (407.0,'Shoes');
--Fila 408
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (408.0,'Automotive');
--Fila 409
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (409.0,'Shoes');
--Fila 410
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (410.0,'Jewelery');
--Fila 411
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (411.0,'Shoes');
--Fila 412
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (412.0,'Baby');
--Fila 413
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (413.0,'Computers');
--Fila 414
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (414.0,'Electronics');
--Fila 415
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (415.0,'Toys');
--Fila 416
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (416.0,'Games');
--Fila 417
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (417.0,'Electronics');
--Fila 418
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (418.0,'Outdoors');
--Fila 419
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (419.0,'Toys');
--Fila 420
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (420.0,'Baby');
--Fila 421
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (421.0,'Tools');
--Fila 422
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (422.0,'Shoes');
--Fila 423
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (423.0,'Books');
--Fila 424
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (424.0,'Shoes');
--Fila 425
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (425.0,'Movies');
--Fila 426
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (426.0,'Clothing');
--Fila 427
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (427.0,'Garden');
--Fila 428
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (428.0,'Games');
--Fila 429
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (429.0,'Beauty');
--Fila 430
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (430.0,'Jewelery');
--Fila 431
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (431.0,'Games');
--Fila 432
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (432.0,'Grocery');
--Fila 433
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (433.0,'Tools');
--Fila 434
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (434.0,'Health');
--Fila 435
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (435.0,'Movies');
--Fila 436
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (436.0,'Health');
--Fila 437
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (437.0,'Computers');
--Fila 438
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (438.0,'Beauty');
--Fila 439
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (439.0,'Shoes');
--Fila 440
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (440.0,'Music');
--Fila 441
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (441.0,'Automotive');
--Fila 442
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (442.0,'Clothing');
--Fila 443
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (443.0,'Home');
--Fila 444
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (444.0,'Movies');
--Fila 445
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (445.0,'Jewelery');
--Fila 446
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (446.0,'Health');
--Fila 447
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (447.0,'Baby');
--Fila 448
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (448.0,'Clothing');
--Fila 449
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (449.0,'Home');
--Fila 450
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (450.0,'Garden');
--Fila 451
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (451.0,'Toys');
--Fila 452
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (452.0,'Beauty');
--Fila 453
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (453.0,'Sports');
--Fila 454
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (454.0,'Electronics');
--Fila 455
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (455.0,'Health');
--Fila 456
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (456.0,'Health');
--Fila 457
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (457.0,'Electronics');
--Fila 458
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (458.0,'Beauty');
--Fila 459
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (459.0,'Industrial');
--Fila 460
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (460.0,'Computers');
--Fila 461
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (461.0,'Shoes');
--Fila 462
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (462.0,'Music');
--Fila 463
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (463.0,'Health');
--Fila 464
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (464.0,'Movies');
--Fila 465
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (465.0,'Toys');
--Fila 466
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (466.0,'Shoes');
--Fila 467
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (467.0,'Outdoors');
--Fila 468
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (468.0,'Garden');
--Fila 469
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (469.0,'Clothing');
--Fila 470
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (470.0,'Garden');
--Fila 471
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (471.0,'Kids');
--Fila 472
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (472.0,'Clothing');
--Fila 473
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (473.0,'Kids');
--Fila 474
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (474.0,'Kids');
--Fila 475
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (475.0,'Garden');
--Fila 476
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (476.0,'Movies');
--Fila 477
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (477.0,'Beauty');
--Fila 478
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (478.0,'Industrial');
--Fila 479
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (479.0,'Computers');
--Fila 480
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (480.0,'Health');
--Fila 481
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (481.0,'Games');
--Fila 482
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (482.0,'Outdoors');
--Fila 483
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (483.0,'Sports');
--Fila 484
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (484.0,'Garden');
--Fila 485
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (485.0,'Music');
--Fila 486
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (486.0,'Beauty');
--Fila 487
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (487.0,'Health');
--Fila 488
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (488.0,'Health');
--Fila 489
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (489.0,'Tools');
--Fila 490
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (490.0,'Garden');
--Fila 491
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (491.0,'Clothing');
--Fila 492
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (492.0,'Beauty');
--Fila 493
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (493.0,'Industrial');
--Fila 494
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (494.0,'Automotive');
--Fila 495
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (495.0,'Books');
--Fila 496
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (496.0,'Clothing');
--Fila 497
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (497.0,'Sports');
--Fila 498
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (498.0,'Games');
--Fila 499
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (499.0,'Automotive');
--Fila 500
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (500.0,'Sports');
--Fila 501
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (501.0,'Electronics');
--Fila 502
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (502.0,'Toys');
--Fila 503
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (503.0,'Sports');
--Fila 504
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (504.0,'Jewelery');
--Fila 505
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (505.0,'Books');
--Fila 506
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (506.0,'Clothing');
--Fila 507
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (507.0,'Home');
--Fila 508
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (508.0,'Shoes');
--Fila 509
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (509.0,'Health');
--Fila 510
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (510.0,'Kids');
--Fila 511
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (511.0,'Jewelery');
--Fila 512
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (512.0,'Clothing');
--Fila 513
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (513.0,'Grocery');
--Fila 514
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (514.0,'Automotive');
--Fila 515
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (515.0,'Industrial');
--Fila 516
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (516.0,'Health');
--Fila 517
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (517.0,'Games');
--Fila 518
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (518.0,'Jewelery');
--Fila 519
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (519.0,'Beauty');
--Fila 520
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (520.0,'Music');
--Fila 521
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (521.0,'Jewelery');
--Fila 522
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (522.0,'Games');
--Fila 523
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (523.0,'Computers');
--Fila 524
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (524.0,'Games');
--Fila 525
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (525.0,'Tools');
--Fila 526
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (526.0,'Tools');
--Fila 527
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (527.0,'Garden');
--Fila 528
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (528.0,'Electronics');
--Fila 529
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (529.0,'Music');
--Fila 530
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (530.0,'Tools');
--Fila 531
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (531.0,'Beauty');
--Fila 532
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (532.0,'Kids');
--Fila 533
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (533.0,'Industrial');
--Fila 534
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (534.0,'Sports');
--Fila 535
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (535.0,'Health');
--Fila 536
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (536.0,'Kids');
--Fila 537
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (537.0,'Beauty');
--Fila 538
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (538.0,'Clothing');
--Fila 539
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (539.0,'Books');
--Fila 540
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (540.0,'Games');
--Fila 541
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (541.0,'Tools');
--Fila 542
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (542.0,'Toys');
--Fila 543
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (543.0,'Clothing');
--Fila 544
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (544.0,'Books');
--Fila 545
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (545.0,'Beauty');
--Fila 546
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (546.0,'Computers');
--Fila 547
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (547.0,'Electronics');
--Fila 548
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (548.0,'Beauty');
--Fila 549
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (549.0,'Computers');
--Fila 550
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (550.0,'Computers');
--Fila 551
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (551.0,'Sports');
--Fila 552
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (552.0,'Industrial');
--Fila 553
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (553.0,'Beauty');
--Fila 554
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (554.0,'Grocery');
--Fila 555
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (555.0,'Toys');
--Fila 556
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (556.0,'Automotive');
--Fila 557
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (557.0,'Jewelery');
--Fila 558
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (558.0,'Movies');
--Fila 559
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (559.0,'Home');
--Fila 560
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (560.0,'Shoes');
--Fila 561
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (561.0,'Home');
--Fila 562
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (562.0,'Kids');
--Fila 563
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (563.0,'Toys');
--Fila 564
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (564.0,'Clothing');
--Fila 565
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (565.0,'Baby');
--Fila 566
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (566.0,'Beauty');
--Fila 567
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (567.0,'Baby');
--Fila 568
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (568.0,'Industrial');
--Fila 569
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (569.0,'Clothing');
--Fila 570
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (570.0,'Toys');
--Fila 571
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (571.0,'Music');
--Fila 572
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (572.0,'Electronics');
--Fila 573
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (573.0,'Home');
--Fila 574
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (574.0,'Sports');
--Fila 575
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (575.0,'Home');
--Fila 576
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (576.0,'Home');
--Fila 577
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (577.0,'Garden');
--Fila 578
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (578.0,'Toys');
--Fila 579
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (579.0,'Shoes');
--Fila 580
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (580.0,'Baby');
--Fila 581
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (581.0,'Beauty');
--Fila 582
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (582.0,'Jewelery');
--Fila 583
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (583.0,'Outdoors');
--Fila 584
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (584.0,'Kids');
--Fila 585
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (585.0,'Sports');
--Fila 586
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (586.0,'Grocery');
--Fila 587
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (587.0,'Kids');
--Fila 588
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (588.0,'Home');
--Fila 589
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (589.0,'Movies');
--Fila 590
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (590.0,'Clothing');
--Fila 591
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (591.0,'Music');
--Fila 592
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (592.0,'Movies');
--Fila 593
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (593.0,'Garden');
--Fila 594
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (594.0,'Shoes');
--Fila 595
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (595.0,'Home');
--Fila 596
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (596.0,'Computers');
--Fila 597
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (597.0,'Automotive');
--Fila 598
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (598.0,'Sports');
--Fila 599
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (599.0,'Home');
--Fila 600
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (600.0,'Garden');
--Fila 601
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (601.0,'Shoes');
--Fila 602
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (602.0,'Baby');
--Fila 603
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (603.0,'Kids');
--Fila 604
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (604.0,'Computers');
--Fila 605
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (605.0,'Clothing');
--Fila 606
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (606.0,'Music');
--Fila 607
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (607.0,'Outdoors');
--Fila 608
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (608.0,'Automotive');
--Fila 609
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (609.0,'Shoes');
--Fila 610
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (610.0,'Kids');
--Fila 611
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (611.0,'Health');
--Fila 612
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (612.0,'Beauty');
--Fila 613
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (613.0,'Grocery');
--Fila 614
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (614.0,'Toys');
--Fila 615
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (615.0,'Music');
--Fila 616
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (616.0,'Music');
--Fila 617
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (617.0,'Grocery');
--Fila 618
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (618.0,'Tools');
--Fila 619
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (619.0,'Clothing');
--Fila 620
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (620.0,'Games');
--Fila 621
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (621.0,'Books');
--Fila 622
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (622.0,'Electronics');
--Fila 623
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (623.0,'Computers');
--Fila 624
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (624.0,'Computers');
--Fila 625
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (625.0,'Kids');
--Fila 626
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (626.0,'Music');
--Fila 627
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (627.0,'Health');
--Fila 628
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (628.0,'Garden');
--Fila 629
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (629.0,'Beauty');
--Fila 630
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (630.0,'Jewelery');
--Fila 631
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (631.0,'Automotive');
--Fila 632
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (632.0,'Toys');
--Fila 633
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (633.0,'Industrial');
--Fila 634
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (634.0,'Toys');
--Fila 635
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (635.0,'Home');
--Fila 636
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (636.0,'Home');
--Fila 637
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (637.0,'Jewelery');
--Fila 638
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (638.0,'Movies');
--Fila 639
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (639.0,'Automotive');
--Fila 640
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (640.0,'Shoes');
--Fila 641
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (641.0,'Health');
--Fila 642
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (642.0,'Jewelery');
--Fila 643
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (643.0,'Music');
--Fila 644
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (644.0,'Clothing');
--Fila 645
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (645.0,'Baby');
--Fila 646
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (646.0,'Automotive');
--Fila 647
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (647.0,'Home');
--Fila 648
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (648.0,'Books');
--Fila 649
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (649.0,'Movies');
--Fila 650
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (650.0,'Movies');
--Fila 651
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (651.0,'Clothing');
--Fila 652
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (652.0,'Clothing');
--Fila 653
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (653.0,'Baby');
--Fila 654
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (654.0,'Automotive');
--Fila 655
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (655.0,'Clothing');
--Fila 656
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (656.0,'Tools');
--Fila 657
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (657.0,'Kids');
--Fila 658
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (658.0,'Books');
--Fila 659
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (659.0,'Computers');
--Fila 660
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (660.0,'Garden');
--Fila 661
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (661.0,'Outdoors');
--Fila 662
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (662.0,'Baby');
--Fila 663
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (663.0,'Toys');
--Fila 664
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (664.0,'Games');
--Fila 665
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (665.0,'Home');
--Fila 666
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (666.0,'Electronics');
--Fila 667
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (667.0,'Beauty');
--Fila 668
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (668.0,'Grocery');
--Fila 669
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (669.0,'Tools');
--Fila 670
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (670.0,'Music');
--Fila 671
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (671.0,'Health');
--Fila 672
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (672.0,'Clothing');
--Fila 673
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (673.0,'Music');
--Fila 674
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (674.0,'Sports');
--Fila 675
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (675.0,'Automotive');
--Fila 676
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (676.0,'Music');
--Fila 677
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (677.0,'Garden');
--Fila 678
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (678.0,'Kids');
--Fila 679
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (679.0,'Kids');
--Fila 680
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (680.0,'Books');
--Fila 681
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (681.0,'Shoes');
--Fila 682
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (682.0,'Electronics');
--Fila 683
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (683.0,'Health');
--Fila 684
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (684.0,'Beauty');
--Fila 685
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (685.0,'Games');
--Fila 686
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (686.0,'Baby');
--Fila 687
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (687.0,'Electronics');
--Fila 688
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (688.0,'Electronics');
--Fila 689
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (689.0,'Movies');
--Fila 690
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (690.0,'Beauty');
--Fila 691
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (691.0,'Books');
--Fila 692
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (692.0,'Home');
--Fila 693
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (693.0,'Electronics');
--Fila 694
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (694.0,'Garden');
--Fila 695
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (695.0,'Health');
--Fila 696
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (696.0,'Movies');
--Fila 697
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (697.0,'Tools');
--Fila 698
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (698.0,'Movies');
--Fila 699
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (699.0,'Toys');
--Fila 700
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (700.0,'Movies');
--Fila 701
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (701.0,'Games');
--Fila 702
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (702.0,'Clothing');
--Fila 703
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (703.0,'Jewelery');
--Fila 704
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (704.0,'Automotive');
--Fila 705
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (705.0,'Jewelery');
--Fila 706
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (706.0,'Shoes');
--Fila 707
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (707.0,'Health');
--Fila 708
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (708.0,'Movies');
--Fila 709
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (709.0,'Sports');
--Fila 710
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (710.0,'Outdoors');
--Fila 711
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (711.0,'Baby');
--Fila 712
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (712.0,'Music');
--Fila 713
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (713.0,'Automotive');
--Fila 714
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (714.0,'Baby');
--Fila 715
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (715.0,'Music');
--Fila 716
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (716.0,'Computers');
--Fila 717
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (717.0,'Automotive');
--Fila 718
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (718.0,'Industrial');
--Fila 719
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (719.0,'Shoes');
--Fila 720
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (720.0,'Health');
--Fila 721
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (721.0,'Shoes');
--Fila 722
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (722.0,'Sports');
--Fila 723
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (723.0,'Baby');
--Fila 724
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (724.0,'Jewelery');
--Fila 725
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (725.0,'Health');
--Fila 726
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (726.0,'Sports');
--Fila 727
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (727.0,'Music');
--Fila 728
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (728.0,'Sports');
--Fila 729
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (729.0,'Clothing');
--Fila 730
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (730.0,'Home');
--Fila 731
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (731.0,'Garden');
--Fila 732
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (732.0,'Games');
--Fila 733
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (733.0,'Beauty');
--Fila 734
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (734.0,'Music');
--Fila 735
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (735.0,'Computers');
--Fila 736
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (736.0,'Games');
--Fila 737
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (737.0,'Jewelery');
--Fila 738
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (738.0,'Automotive');
--Fila 739
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (739.0,'Games');
--Fila 740
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (740.0,'Industrial');
--Fila 741
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (741.0,'Sports');
--Fila 742
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (742.0,'Outdoors');
--Fila 743
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (743.0,'Books');
--Fila 744
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (744.0,'Jewelery');
--Fila 745
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (745.0,'Garden');
--Fila 746
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (746.0,'Electronics');
--Fila 747
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (747.0,'Jewelery');
--Fila 748
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (748.0,'Baby');
--Fila 749
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (749.0,'Music');
--Fila 750
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (750.0,'Garden');
--Fila 751
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (751.0,'Sports');
--Fila 752
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (752.0,'Beauty');
--Fila 753
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (753.0,'Books');
--Fila 754
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (754.0,'Health');
--Fila 755
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (755.0,'Books');
--Fila 756
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (756.0,'Garden');
--Fila 757
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (757.0,'Home');
--Fila 758
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (758.0,'Clothing');
--Fila 759
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (759.0,'Baby');
--Fila 760
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (760.0,'Kids');
--Fila 761
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (761.0,'Automotive');
--Fila 762
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (762.0,'Books');
--Fila 763
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (763.0,'Automotive');
--Fila 764
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (764.0,'Books');
--Fila 765
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (765.0,'Outdoors');
--Fila 766
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (766.0,'Outdoors');
--Fila 767
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (767.0,'Music');
--Fila 768
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (768.0,'Tools');
--Fila 769
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (769.0,'Computers');
--Fila 770
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (770.0,'Health');
--Fila 771
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (771.0,'Games');
--Fila 772
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (772.0,'Tools');
--Fila 773
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (773.0,'Home');
--Fila 774
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (774.0,'Sports');
--Fila 775
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (775.0,'Sports');
--Fila 776
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (776.0,'Grocery');
--Fila 777
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (777.0,'Computers');
--Fila 778
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (778.0,'Tools');
--Fila 779
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (779.0,'Outdoors');
--Fila 780
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (780.0,'Music');
--Fila 781
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (781.0,'Clothing');
--Fila 782
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (782.0,'Movies');
--Fila 783
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (783.0,'Movies');
--Fila 784
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (784.0,'Industrial');
--Fila 785
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (785.0,'Clothing');
--Fila 786
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (786.0,'Music');
--Fila 787
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (787.0,'Garden');
--Fila 788
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (788.0,'Movies');
--Fila 789
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (789.0,'Movies');
--Fila 790
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (790.0,'Beauty');
--Fila 791
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (791.0,'Home');
--Fila 792
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (792.0,'Beauty');
--Fila 793
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (793.0,'Grocery');
--Fila 794
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (794.0,'Toys');
--Fila 795
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (795.0,'Games');
--Fila 796
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (796.0,'Shoes');
--Fila 797
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (797.0,'Home');
--Fila 798
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (798.0,'Computers');
--Fila 799
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (799.0,'Clothing');
--Fila 800
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (800.0,'Kids');
--Fila 801
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (801.0,'Home');
--Fila 802
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (802.0,'Sports');
--Fila 803
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (803.0,'Jewelery');
--Fila 804
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (804.0,'Jewelery');
--Fila 805
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (805.0,'Electronics');
--Fila 806
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (806.0,'Games');
--Fila 807
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (807.0,'Movies');
--Fila 808
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (808.0,'Industrial');
--Fila 809
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (809.0,'Clothing');
--Fila 810
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (810.0,'Movies');
--Fila 811
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (811.0,'Health');
--Fila 812
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (812.0,'Health');
--Fila 813
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (813.0,'Outdoors');
--Fila 814
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (814.0,'Electronics');
--Fila 815
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (815.0,'Kids');
--Fila 816
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (816.0,'Health');
--Fila 817
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (817.0,'Shoes');
--Fila 818
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (818.0,'Jewelery');
--Fila 819
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (819.0,'Home');
--Fila 820
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (820.0,'Beauty');
--Fila 821
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (821.0,'Computers');
--Fila 822
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (822.0,'Outdoors');
--Fila 823
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (823.0,'Outdoors');
--Fila 824
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (824.0,'Computers');
--Fila 825
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (825.0,'Sports');
--Fila 826
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (826.0,'Tools');
--Fila 827
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (827.0,'Electronics');
--Fila 828
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (828.0,'Automotive');
--Fila 829
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (829.0,'Health');
--Fila 830
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (830.0,'Computers');
--Fila 831
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (831.0,'Garden');
--Fila 832
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (832.0,'Games');
--Fila 833
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (833.0,'Clothing');
--Fila 834
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (834.0,'Home');
--Fila 835
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (835.0,'Industrial');
--Fila 836
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (836.0,'Garden');
--Fila 837
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (837.0,'Computers');
--Fila 838
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (838.0,'Industrial');
--Fila 839
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (839.0,'Tools');
--Fila 840
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (840.0,'Grocery');
--Fila 841
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (841.0,'Music');
--Fila 842
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (842.0,'Automotive');
--Fila 843
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (843.0,'Kids');
--Fila 844
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (844.0,'Health');
--Fila 845
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (845.0,'Kids');
--Fila 846
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (846.0,'Home');
--Fila 847
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (847.0,'Computers');
--Fila 848
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (848.0,'Garden');
--Fila 849
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (849.0,'Games');
--Fila 850
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (850.0,'Shoes');
--Fila 851
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (851.0,'Shoes');
--Fila 852
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (852.0,'Grocery');
--Fila 853
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (853.0,'Games');
--Fila 854
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (854.0,'Industrial');
--Fila 855
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (855.0,'Sports');
--Fila 856
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (856.0,'Shoes');
--Fila 857
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (857.0,'Health');
--Fila 858
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (858.0,'Garden');
--Fila 859
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (859.0,'Health');
--Fila 860
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (860.0,'Computers');
--Fila 861
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (861.0,'Music');
--Fila 862
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (862.0,'Games');
--Fila 863
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (863.0,'Electronics');
--Fila 864
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (864.0,'Computers');
--Fila 865
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (865.0,'Music');
--Fila 866
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (866.0,'Grocery');
--Fila 867
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (867.0,'Automotive');
--Fila 868
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (868.0,'Home');
--Fila 869
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (869.0,'Kids');
--Fila 870
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (870.0,'Outdoors');
--Fila 871
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (871.0,'Toys');
--Fila 872
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (872.0,'Home');
--Fila 873
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (873.0,'Industrial');
--Fila 874
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (874.0,'Grocery');
--Fila 875
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (875.0,'Electronics');
--Fila 876
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (876.0,'Sports');
--Fila 877
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (877.0,'Toys');
--Fila 878
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (878.0,'Sports');
--Fila 879
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (879.0,'Music');
--Fila 880
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (880.0,'Industrial');
--Fila 881
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (881.0,'Baby');
--Fila 882
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (882.0,'Jewelery');
--Fila 883
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (883.0,'Grocery');
--Fila 884
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (884.0,'Electronics');
--Fila 885
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (885.0,'Toys');
--Fila 886
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (886.0,'Baby');
--Fila 887
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (887.0,'Electronics');
--Fila 888
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (888.0,'Outdoors');
--Fila 889
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (889.0,'Books');
--Fila 890
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (890.0,'Games');
--Fila 891
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (891.0,'Computers');
--Fila 892
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (892.0,'Automotive');
--Fila 893
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (893.0,'Games');
--Fila 894
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (894.0,'Automotive');
--Fila 895
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (895.0,'Shoes');
--Fila 896
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (896.0,'Home');
--Fila 897
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (897.0,'Home');
--Fila 898
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (898.0,'Kids');
--Fila 899
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (899.0,'Shoes');
--Fila 900
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (900.0,'Sports');
--Fila 901
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (901.0,'Sports');
--Fila 902
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (902.0,'Music');
--Fila 903
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (903.0,'Grocery');
--Fila 904
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (904.0,'Kids');
--Fila 905
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (905.0,'Garden');
--Fila 906
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (906.0,'Clothing');
--Fila 907
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (907.0,'Jewelery');
--Fila 908
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (908.0,'Health');
--Fila 909
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (909.0,'Kids');
--Fila 910
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (910.0,'Toys');
--Fila 911
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (911.0,'Kids');
--Fila 912
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (912.0,'Toys');
--Fila 913
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (913.0,'Grocery');
--Fila 914
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (914.0,'Garden');
--Fila 915
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (915.0,'Automotive');
--Fila 916
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (916.0,'Automotive');
--Fila 917
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (917.0,'Automotive');
--Fila 918
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (918.0,'Automotive');
--Fila 919
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (919.0,'Clothing');
--Fila 920
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (920.0,'Computers');
--Fila 921
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (921.0,'Clothing');
--Fila 922
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (922.0,'Jewelery');
--Fila 923
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (923.0,'Sports');
--Fila 924
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (924.0,'Beauty');
--Fila 925
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (925.0,'Home');
--Fila 926
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (926.0,'Outdoors');
--Fila 927
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (927.0,'Beauty');
--Fila 928
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (928.0,'Beauty');
--Fila 929
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (929.0,'Outdoors');
--Fila 930
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (930.0,'Electronics');
--Fila 931
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (931.0,'Toys');
--Fila 932
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (932.0,'Sports');
--Fila 933
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (933.0,'Baby');
--Fila 934
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (934.0,'Books');
--Fila 935
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (935.0,'Movies');
--Fila 936
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (936.0,'Clothing');
--Fila 937
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (937.0,'Beauty');
--Fila 938
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (938.0,'Sports');
--Fila 939
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (939.0,'Computers');
--Fila 940
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (940.0,'Books');
--Fila 941
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (941.0,'Sports');
--Fila 942
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (942.0,'Sports');
--Fila 943
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (943.0,'Jewelery');
--Fila 944
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (944.0,'Garden');
--Fila 945
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (945.0,'Grocery');
--Fila 946
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (946.0,'Beauty');
--Fila 947
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (947.0,'Books');
--Fila 948
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (948.0,'Home');
--Fila 949
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (949.0,'Health');
--Fila 950
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (950.0,'Movies');
--Fila 951
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (951.0,'Books');
--Fila 952
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (952.0,'Baby');
--Fila 953
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (953.0,'Clothing');
--Fila 954
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (954.0,'Baby');
--Fila 955
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (955.0,'Health');
--Fila 956
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (956.0,'Movies');
--Fila 957
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (957.0,'Computers');
--Fila 958
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (958.0,'Garden');
--Fila 959
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (959.0,'Automotive');
--Fila 960
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (960.0,'Shoes');
--Fila 961
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (961.0,'Electronics');
--Fila 962
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (962.0,'Health');
--Fila 963
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (963.0,'Games');
--Fila 964
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (964.0,'Garden');
--Fila 965
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (965.0,'Industrial');
--Fila 966
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (966.0,'Toys');
--Fila 967
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (967.0,'Toys');
--Fila 968
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (968.0,'Sports');
--Fila 969
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (969.0,'Computers');
--Fila 970
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (970.0,'Shoes');
--Fila 971
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (971.0,'Music');
--Fila 972
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (972.0,'Games');
--Fila 973
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (973.0,'Automotive');
--Fila 974
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (974.0,'Games');
--Fila 975
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (975.0,'Games');
--Fila 976
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (976.0,'Outdoors');
--Fila 977
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (977.0,'Computers');
--Fila 978
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (978.0,'Automotive');
--Fila 979
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (979.0,'Garden');
--Fila 980
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (980.0,'Music');
--Fila 981
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (981.0,'Beauty');
--Fila 982
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (982.0,'Tools');
--Fila 983
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (983.0,'Games');
--Fila 984
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (984.0,'Tools');
--Fila 985
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (985.0,'Beauty');
--Fila 986
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (986.0,'Automotive');
--Fila 987
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (987.0,'Electronics');
--Fila 988
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (988.0,'Home');
--Fila 989
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (989.0,'Industrial');
--Fila 990
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (990.0,'Automotive');
--Fila 991
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (991.0,'Grocery');
--Fila 992
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (992.0,'Industrial');
--Fila 993
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (993.0,'Beauty');
--Fila 994
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (994.0,'Kids');
--Fila 995
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (995.0,'Outdoors');
--Fila 996
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (996.0,'Baby');
--Fila 997
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (997.0,'Computers');
--Fila 998
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (998.0,'Computers');
--Fila 999
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (999.0,'Toys');
--Fila 1.000
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (1000.0,'Music');
