INSERT INTO LLEGADAPEDIDO (CODIGOPEDIDO,FECHAENTREGA,CANTIDADPRODUCTOS,CALIDADPRODUCTOS,CALIFICACION) VALUES(1,TO_DATE('2018/11/10','yyyy/mm/dd'),50,'BUENA','BIEN');

SELECT CODIGOPRODUCTO, CANTIDADPRODUCTOS+CANTIDAD AS NUEVA_CANTIDAD
FROM(
    SELECT CODIGOPRODUCTO,CODIGOPEDIDO, CANTIDAD FROM PRODUCTOPEDIDO proPed INNER JOIN PRODUCTO pro ON proped.codigoproducto= pro.codigodebarras WHERE proPed.CODIGOPEDIDO ='50'
    )u INNER JOIN LLEGADAPEDIDO ped ON u.CODIGOPEDIDO = ped.CODIGOPEDIDO
;
commit;
