
SELECT * FROM PEDIDO;
--Creo nuevo pedido
INSERT INTO PEDIDO (CODIGOPEDIDO,FECHAENTREGA,PRECIOTOTAL,ESTADOORDEN,NITPROVEEDOR, IDSUCURSAL) 
    VALUES(578,TO_DATE('2018/11/10','yyyy/mm/dd'),50,'PROCESO','400500080-5',1);

 --Actualizo los productos del pedido
UPDATE PRODUCTOPEDIDO pp
    SET pp.codigoproducto=578 
WHERE EXISTS(
    SELECT * FROM PEDIDO 
    
);


    
DELETE FROM PEDIDO WHERE codigopedido!=578 AND nitproveedor='40050080-5';
commit;
rollback;    
SELECT * FROM PRODUCTOPEDIDO;
SELECT * FROM PRODUCTOPEDIDO pp INNER JOIN PEDIDO p ON pp.codigopedido=p.codigopedido ;
SELECT * FROM LLEGADAPEDIDO;