-- Primero creamos las sucursales deben crearse las sucursales RF4
--Luego se crean categorias y productos, RF2
-- Creamos los estantes y las asociamos 
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (1, 1, 1, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (1, 2, 2, 1000,1000,1000,1000,120);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (1, 3, 3, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (2, 4, 1, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (2, 5, 2, 1000,1000,1000,1000,120);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (2, 6, 3, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (3, 7, 1, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (3, 8, 2, 1000,1000,1000,1000,120);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (3, 9, 3, 500,500,500,500,60);

INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (4, 10, 1, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (4, 11, 2, 1000,1000,1000,1000,120);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (4, 12, 3, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (5, 13, 1, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (5, 14, 2, 1000,1000,1000,1000,120);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (5, 15, 3, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (6, 16, 1, 500,500,500,500,60);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (6, 17, 2, 1000,1000,1000,1000,120);
INSERT INTO ESTANTE (IDSUCURSAL,IDESTANTE,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO,NIVELDEABASTECIMIENTO) VALUES (6, 18, 3, 500,500,500,500,60);

--Anade los productos a sus estantes respectivos
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (1,'57d9b18e',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (2,'cfd36e72',29);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (3,'113a25be9',56);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (4,'57d9b18e',28);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (5,'cfd36e72',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (6,'113a25be9',29);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (7,'57d9b18e',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (8,'cfd36e72',29);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (9,'113a25be9',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (10,'57d9b18e',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (11,'cfd36e72',29);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (12,'113a25be9',56);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (13,'57d9b18e',28);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (14,'cfd36e72',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (15,'113a25be9',29);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (16,'57d9b18e',20);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (17,'cfd36e72',29);
INSERT INTO ESTANTEPRODUCTO (idEstante, idProducto, cantidad) VALUES (18,'113a25be9',20);
commit;