INSERT INTO PRODUCTOOFRECIDOSUCURSAL (IDSUCURSAL,CODIGOBARRAS,PRECIOUNITARIO,PRECIOUNIDADMEDIDA,NIVELDEREORDEN,CANTIDADRECOMPRA, cantidad) VALUES(1,'10893f3ea',500,2,50,2,100);
INSERT INTO PRODUCTOOFRECIDOSUCURSAL (IDSUCURSAL,CODIGOBARRAS,PRECIOUNITARIO,PRECIOUNIDADMEDIDA,NIVELDEREORDEN,CANTIDADRECOMPRA, cantidad) VALUES(1,'4f918bc6',50,2,50,2,50);
INSERT INTO PRODUCTOOFRECIDOSUCURSAL (IDSUCURSAL,CODIGOBARRAS,PRECIOUNITARIO,PRECIOUNIDADMEDIDA,NIVELDEREORDEN,CANTIDADRECOMPRA, cantidad) VALUES(2,'1fb6498b1',70,2,50,2,200);


--Muestra todos los productos
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras;
--Muestra productos con precio mayor a 10 menor a 100
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras WHERE PRECIOUNITARIO BETWEEN 10 AND 100;
--Muestra productos con cantidad volumen mayor a 10 menor a 200 cm^3
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras WHERE prod.unidaddemedida ='cm^3' AND prod.especificacionempacado BETWEEN 100 AND 1100;
--Muestra productos con cantidad peso mayor a 10 menor a 200 gr
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras WHERE UNIDADDEMEDIDA='gr' AND prod.especificacionempacado BETWEEN 10 AND 200;

SELECT * FROM proveedorproducto prov INNER JOIN PRODUCTO prod  ON prov.codigoproducto = prod.codigodebarras WHERE prov.nitproveedor = '100300020-1'

