--�Por convenci�n para una empresa el nombre es su raz�n social y el apellido el tipo de sociedad.

-- Creamos 3 clientes de tipo persona natural
INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, poseeCarro) VALUES ('CC','1234567',0);
INSERT INTO PERSONANATURAL (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, CORREO) VALUES ('CC','1234567', 'Sandra','sandra@gmail.com');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, poseeCarro) VALUES ('CC','8765',0);
INSERT INTO PERSONANATURAL (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, CORREO) VALUES ('CC','8765', 'Carlos','carlos@gmail.com');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, poseeCarro) VALUES ('CC','9876543',0);
INSERT INTO PERSONANATURAL (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, CORREO) VALUES ('CC','9876543', 'Juan','juan@gmail.com');


-- Creamos 3 clientes de tipo persona jur�dica

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, poseeCarro) VALUES ('NIT','89765456',0);
INSERT INTO PERSONAJURIDICA (TIPODOCUMENTO, NUMDOCUMENTO, DIRECCION ) VALUES('NIT','89765456','Calle 2');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, poseeCarro) VALUES ('NIT','7654',0);
INSERT INTO PERSONAJURIDICA (TIPODOCUMENTO, NUMDOCUMENTO, DIRECCION ) VALUES('NIT','7654','Calle 26');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, poseeCarro) VALUES ('NIT','856473',0);
INSERT INTO PERSONAJURIDICA (TIPODOCUMENTO, NUMDOCUMENTO, DIRECCION ) VALUES('NIT','856473','Calle 23');

commit;