INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (100,'Galerias','Psicografica','Grande','Bucaramanga','Calle 45 # 22-31');
INSERT INTO PROVEEDOR (NIT, NOMBRE) VALUES ('400500080-9', 'Cosmeticos LTA');
INSERT INTO PEDIDO (CODIGOPEDIDO,FECHAENTREGA,PRECIOTOTAL,ESTADOORDEN,NITPROVEEDOR) VALUES(50,TO_DATE('2018/11/10','yyyy/mm/dd'),50,'PROCESO','400500080-9');
INSERT INTO PRODUCTOPEDIDO (CODIGOPRODUCTO)
INSERT INTO LLEGADAPEDIDO (CODIGOPEDIDO,IDSUCURSAL,FECHAENTREGA,CANTIDADPRODUCTOS,CALIDADPRODUCTOS,CALIFICACION) VALUES(50,100,TO_DATE('2018/11/10','yyyy/mm/dd'),50,'BUENA','BIEN');
SELECT * FROM PRODUCTOPEDIDO WHERE CODIGOPEDIDO ='50';