INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (100,'Galerias','Psicografica','Grande','Bucaramanga','Calle 45 # 22-31');
INSERT INTO PROVEEDOR (NIT, NOMBRE) VALUES ('400500080-9', 'Cosmeticos LTA');
INSERT INTO PRODUCTO (CODIGODEBARRAS, NOMBRE, PRESENTACION, MARCA, CANTIDAD, UNIDADDEMEDIDA, ESPECIFICACIONEMPACADO) VALUES ('10893f3ea', 'Crema Dental', 'Tubo','Colgate', '100','cm^3', '100 cm^3');
INSERT INTO PRODUCTO (CODIGODEBARRAS, NOMBRE, PRESENTACION, MARCA, CANTIDAD, UNIDADDEMEDIDA, ESPECIFICACIONEMPACADO) VALUES ('239109cc6', 'Crema de afeitar', 'Spray', 'Prestobarba', '300','cm^3', '300 cm^3');


INSERT INTO PEDIDO (CODIGOPEDIDO,FECHAENTREGA,PRECIOTOTAL,ESTADOORDEN,NITPROVEEDOR) VALUES(50,TO_DATE('2018/11/10','yyyy/mm/dd'),50,'PROCESO','400500080-9');
INSERT INTO PRODUCTOPEDIDO (CODIGOPRODUCTO,CODIGOPEDIDO,VOLUMEN,PRECIO) VALUES ('10893f3ea',50,100,200);
