-- Primero creamos las sucursales
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (1,'Galerias','Psicografica','Grande','Bucaramanga','Calle 45 # 22-31');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (2,'Santa Barbara','Geografica','Mediano','Bogota','Carrera 7 #116-40');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (3,'Hayuelos','Demografica','Grande','Cartagena','Calle 8 #76-23');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (4,'Mazuren','Socioeconomica','Grande','Bucaramanga','Autopista Nte #01-12');

-- Creamos 2 categorias de prueba
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (1, 'ASEO PERSONAL');
INSERT INTO CATEGORIA (IDCATEGORIA, TIPOCAT) VALUES (2, 'VERDURAS');

-- Creamos las bodegas y las asociamos 
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (1, 1, 1, 500,500,500,500);

INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (1, 2, 2, 1000,1000,1000,1000);


INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (2, 1, 1, 500,500,500,500);

INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (2, 2, 2, 1000,1000,1000,1000);


INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (3, 1, 1, 500,500,500,500);

INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (3, 2, 2, 1000,1000,1000,1000);


INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (4, 1, 1, 500,500,500,500);

INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,TIPOPRODUCTOID,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (4, 2, 2, 1000,1000,1000,1000);

