-- Inserci�n de sucursales
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (1,'Galerias','Psicografica','Grande','Bucaramanga','Calle 45 # 22-31');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (2,'Santa Barbara','Geografica','Mediano','Bogota','Carrera 7 #116-40');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (3,'Hayuelos','Demografica','Grande','Cartagena','Calle 8 #76-23');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (4,'Mazuren','Socioeconomica','Grande','Bucaramanga','Autopista Nte #01-12');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (5,'Chapinero','Conductual','Grande','Cartagena','Calle 63 #13-22');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (6,'Portal Norte','Conductual','Pequeno','Bogota','Calle 170 #42-15');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (7,'Portal Sur','Conductual','Pequeno','Bucaramanga','Calle 63 Sur #24-15');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (8,'Usme','Psicografica','Pequeno','Cartagena','Calle 45 Sur #68-23');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (9,'Usaquen','Conductual','Mediano','Cartagena','Calle 127 #15-32');
INSERT INTO SUCURSAL (IDSUCURSAL,NOMBRE,SEGMENTACION,TAMANO,CIUDAD,DIRECCION) VALUES (10,'Andino','Conductual','Mediano','Bogota','Calle 82 #13-01');