--�Por convenci�n para una empresa el nombre es su raz�n social y el apellido el tipo de sociedad.

-- Creamos 3 clientes de tipo persona natural
INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, APELLIDO, CORREO) VALUES ('Cedula', '97969419', 'Sandra','Botero', 's.botero@mail.com');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, APELLIDO, CORREO) VALUES ('TI', '32014711', 'Carlos','Gonzalez','c.gonzalez@mail.com');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, APELLIDO, CORREO) VALUES ('Pasaporte', '75166474', 'Juliana','Rodriguez','j.rodriguez@mail.com');

-- Creamos 3 clientes de tipo persona jur�dica

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, APELLIDO, CORREO) VALUES ('NIT', '400300060-2', 'Empresas1','SAS','comercial@emps1.com');

INSERT INTO PERSONAJURIDICA (TIPODOCUMENTO, NUMDOCUMENTO, DIRECCION) VALUES ('NIT', '400300060-2', 'Av. Esperanza # 4-16');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, APELLIDO, CORREO) VALUES ('NIT', '500200060-9', 'Empresas2','LTDA','comercial@emps2.com');

INSERT INTO PERSONAJURIDICA (TIPODOCUMENTO, NUMDOCUMENTO, DIRECCION) VALUES ('NIT', '500200060-9', 'Av. Boyaca # 55-46');

INSERT INTO CLIENTE (TIPODOCUMENTO, NUMDOCUMENTO, NOMBRE, APELLIDO, CORREO) VALUES ('NIT', '500700060-4', 'Empresas3','SA','comercial@emps3.com');

INSERT INTO PERSONAJURIDICA (TIPODOCUMENTO, NUMDOCUMENTO, DIRECCION) VALUES ('NIT', '500700060-4', 'Cll. 45 # 55-46');
