--Las sucursales y productos deben estar creados
-- Creamos las bodegas y las asociamos 
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (1, 1, 1, 500,570,500,570);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (2, 2, 2, 1000,1300,1000,3000);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (3, 3, 1, 500,540,500,550);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (4, 4, 2, 1000,1600,1000,1600);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (5, 5, 1, 500,508,500,550);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (6, 6, 2, 1000,1500,1000,1500);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (7, 7, 1, 500,504,500,560);
INSERT INTO BODEGA (IDSUCURSAL,IDBODEGA,CATEGORIA,CAPACIDADVOLUMEN,CAPACIDADTOTALVOLUMEN,CAPACIDADPESO,CAPACIDADTOTALPESO) VALUES (8, 8, 2, 1000,1600,1000,1040);

commit;
