INSERT INTO PRODUCTOOFRECIDOSUCURSAL (IDSUCURSAL,CODIGOBARRAS,PRECIOUNITARIO,PRECIOUNIDADMEDIDA,NIVELDEREORDEN,CANTIDADRECOMPRA) VALUES(1,'10893f3ea',500,2,50,2);
INSERT INTO PRODUCTOOFRECIDOSUCURSAL (IDSUCURSAL,CODIGOBARRAS,PRECIOUNITARIO,PRECIOUNIDADMEDIDA,NIVELDEREORDEN,CANTIDADRECOMPRA) VALUES(1,'57d9b18e',50,2,50,2);
INSERT INTO PRODUCTOOFRECIDOSUCURSAL (IDSUCURSAL,CODIGOBARRAS,PRECIOUNITARIO,PRECIOUNIDADMEDIDA,NIVELDEREORDEN,CANTIDADRECOMPRA) VALUES(2,'57d9b18e',70,2,50,2);


--Muestra todos los productos
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras;
--Muestra productos con precio mayor a 10 menor a 100
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras WHERE PRECIOUNITARIO BETWEEN 10 AND 100;
--Muestra productos con cantidad volumen mayor a 10 menor a 200 cm^3
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras WHERE UNIDADDEMEDIDA='cm^3' AND CANTIDAD BETWEEN 10 AND 200;
--Muestra productos con cantidad peso mayor a 10 menor a 200 gr
SELECT * FROM PRODUCTOOFRECIDOSUCURSAL suc INNER JOIN PRODUCTO prod ON suc.codigobarras=prod.codigodebarras WHERE UNIDADDEMEDIDA='gr' AND CANTIDAD BETWEEN 10 AND 200;

