INSERT INTO VENTA (NUMEROVENTA,TIPODOCCLIENTE,NUMDOCCLIENTE,FECHAVENTA,TOTAL,TOTALIMPUESTOS,SUCURSAL) 
    VALUES (1,'CC','1234567',TO_DATE('2018/11/10','yyyy/mm/dd'),50000,3400,1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (1,'57d9b18e',10);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (1,'113a25be9',5);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (1,'1a1b593ae',1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (1,'fc9847d6',5);
    
INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (2,'CC','1234567',TO_DATE('2018/10/10','yyyy/mm/dd'),50,5,1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (2,'57d9b18e',1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (2,'113a25be9',15);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (2,'1a1b593ae',2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (2,'fc9847d6',25);
    
INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (3,'CC','8765',TO_DATE('2018/10/11','yyyy/mm/dd'),80,8,1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (3,'57d9b18e',10);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (3,'113a25be9',5);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (3,'1a1b593ae',1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (3,'fd7a5f75',5);

INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (4,'CC','9876543',TO_DATE('2018/10/15','yyyy/mm/dd'),80,8,1); 
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (4,'57d9b18e',10);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (4,'4f918bc6',5);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (4,'154422331',1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (4,'fd7a5f75',5);

INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (5,'CC','8765',TO_DATE('2018/10/22','yyyy/mm/dd'),90,9,1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (5,'57d9b18e',13);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (5,'4f918bc6',2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (5,'154422331',10);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (5,'fd7a5f75',15);

INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (6,'CC','8765',TO_DATE('2018/10/17','yyyy/mm/dd'),500,50,2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (6,'57d9b18e',11);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (6,'4f918bc6',21);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (6,'154422331',3);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (6,'fd7a5f75',1);

INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (7,'CC','8765',TO_DATE('2018/11/11','yyyy/mm/dd'),850,85,2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (7,'57d9b18e',3);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (7,'4f918bc6',2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (7,'154422331',7);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (7,'fd7a5f75',1);

INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (8,'CC','8765',TO_DATE('2018/11/12','yyyy/mm/dd'),80,8,2); 
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (8,'57d9b18e',23);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (8,'4f918bc6',21);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (8,'154422331',4);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (8,'fd7a5f75',12);

INSERT INTO VENTA (numeroVenta,tipoDocCliente,numDocCliente,fechaVenta,total,totalImpuestos,sucursal) 
    VALUES (9,'CC','8765',TO_DATE('2018/10/12','yyyy/mm/dd'),10,1,2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (9,'57d9b18e',1);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (9,'4f918bc6',2);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (9,'154422331',10);
        INSERT INTO VENTAPRODUCTO(NUMEROVENTA,CODIGOPRODUCTO,CANTIDAD)
        VALUES (9,'fd7a5f75',1);
commit;